### ISSUE TITLE
Bug with sending free parking and set player balance

### ISSUE THREAD

**Issue by stewilko84** [brentvollebregt/monopoly-money#1]
I'm really liking this tool, especially as the UK is on lockdown at the minute, and me and a couple of friends want to have a game of monopoly.

I've been testing this before we play, and I have encountered an issue, not sure if it is my OS or Python version; but whenever I set a player balance, or send a player the money from free parking it just sends it to the player who is assigned as the banker - regardless of who I select. I've had a look in the run_server.py and scripts.js files but I'm not proficient in either of them so I'm not entireley sure how the functions are working.

My OS is Windows 10 (version 10.0.18363 Build 18363)
Python 3.8.1

**Comment by brentvollebregt** [comment]
I haven't run this project in years so this will be fun 😂. 
I'll take a look at it.

**Comment by brentvollebregt** [comment]
@stewilko84 managed to fix it, funnily enough, I already had the values there but linked them up wrong.
The changes have been put in master 👍
