### ISSUE TITLE
CORS Policy Error. 

### ISSUE THREAD

**Issue by TheKeySpammer** [brentvollebregt/monopoly-money#11]
All of the browsers now block api request to /api with same origin.

**Comment by brentvollebregt** [comment]
Is this to the hosted demo or a local instance you are running?

**Comment by TheKeySpammer** [comment]
Getting on hosted instance. No 'Access-Control-Allow-Origin' header is present on the requested resource, when I try create game https://monopoly-money.nitratine.net/new-game.

**Comment by brentvollebregt** [comment]
I ran out of dyno hours - wait until the first of next month. 

Need to look at the error and put a message in though.

**Comment by TheKeySpammer** [comment]
Yeah, its fixed now.
