### ISSUE TITLE
FR: Make "free parking" support a configurable option

### ISSUE THREAD

**Issue by mjpieters** [brentvollebregt/monopoly-money#12]
Treating taxes and fees as a pot you can win when you land on the "Free Parking" square, is an optional game rule.

Could this be made a configurable option in the app? This would just hide all free parking UI elements; this reduces accidents when players transfer money.

I guess the changes required would be:

- Funds: Don't show the Free Parking card
- Bank: Hide the Give Free Parking section
- Setting: add a house rules section with a Free Parking checkbox (enabled by default)
- Track the feature state per game.
- Add game events to communicate the state changes.

**Comment by brentvollebregt** [comment]
Thanks for the recommendation and the change 👌

I'm currently out of mins on Heroku but should have a new lot in a day - will need to trigger the build from GitHub pipelines again to get it into Heroku.
