### ISSUE TITLE
WebSocket disconnects constantly while game is in session

### ISSUE THREAD

**Issue by artineering** [brentvollebregt/monopoly-money#2]
The websocket connection keeps dropping for all the players. Is it possible to add a heartbeat callback to the clients so that it can keep the websocket alive?

**Comment by brentvollebregt** [comment]
Is this occurring when using your own instance or the public instance? 

This is known to occur on the public instance quite a bit - I believe it's due to it's hosted on Heroku.

**Comment by artineering** [comment]
This is happening in the public instance. You are right about private instance on Heroku also adding its own problems.

**Comment by brentvollebregt** [comment]
When you say "also adding its own problems", are you finding this is occurring on a local running instance? I do not have this happen locally.

If we can identify what is happening on Heroku (and potentially your local instance) then I can look into it otherwise I have nothing to go off unfortunately.

**Comment by brentvollebregt** [comment]
@artineering I was looking at the network graph on GitHub for this repo and noticed you had a fix to this in your repo!

I made similar changes in 320de6e845ff2967e78c216b71a2382753819029 - this makes the client send a message to the server every 10 seconds. I [saw on the Heroku docs](https://devcenter.heroku.com/articles/websockets#timeouts) that WebSockets have the same timeouts as HTTP timeouts on Heroku, which is [55 seconds after an initial lot of data is sent](https://devcenter.heroku.com/articles/http-routing#timeouts).

I'll close this issue as I believe this has fixed it. Let me know if it has not.
