### ISSUE TITLE
Can't create new game

### ISSUE THREAD

**Issue by michaeljandrews** [brentvollebregt/monopoly-money#5]
UPDATE-- See comment below

Hi,
   I'm following the install instructions, using the example .env files, and when attempting to build the dependencies, this error appears:

src/api/dto.ts:1:27 - error TS2307: Cannot find module '@monopoly-money/game-state'.

1 import { GameEvent } from "@monopoly-money/game-state";
                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/gameStore/Game.ts:11:8 - error TS2307: Cannot find module '@monopoly-money/game-state'.

11 } from "@monopoly-money/game-state";
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/gameStore/Game.ts:41:49 - error TS7006: Parameter 'p' implicitly has an 'any' type.

41     const player = this.gameState.players.find((p) => p.playerId === playerId);
                                                   ~

src/gameStore/Game.ts:88:38 - error TS7006: Parameter 'p' implicitly has an 'any' type.

88     if (this.gameState.players.find((p) => p.playerId) !== undefined) {
                                        ~

src/gameStore/Game.ts:142:58 - error TS7006: Parameter 'p' implicitly has an 'any' type.

142     const bankerPlayers = this.gameState.players.filter((p) => p.banker);

The detailed log file looks like this:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@6.14.6
3 info using node@v12.18.3
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle monopoly-money@~prebuild: monopoly-money@
6 info lifecycle monopoly-money@~build: monopoly-money@
7 verbose lifecycle monopoly-money@~build: unsafe-perm in lifecycle true
8 verbose lifecycle monopoly-money@~build: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/pi/projects/monopoly-money/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sb$
9 verbose lifecycle monopoly-money@~build: CWD: /home/pi/projects/monopoly-money
10 silly lifecycle monopoly-money@~build: Args: [
10 silly lifecycle   '-c',
10 silly lifecycle   'cd packages/game-state && npm run build && cd ../server && npm run build && cd ../client && npm run build && cd ../../ && node postbuild.js'
10 silly lifecycle ]
11 silly lifecycle monopoly-money@~build: Returned: code: 2  signal: null
12 info lifecycle monopoly-money@~build: Failed to exec build script
13 verbose stack Error: monopoly-money@ build: `cd packages/game-state && npm run build && cd ../server && npm run build && cd ../client && npm run build && cd ../../ && node postbuild.js`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid monopoly-money@
15 verbose cwd /home/pi/projects/monopoly-money
16 verbose Linux 5.4.51-v7+
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
18 verbose node v12.18.3
19 verbose npm  v6.14.6
20 error code ELIFECYCLE
21 error errno 2
22 error monopoly-money@ build: `cd packages/game-state && npm run build && cd ../server && npm run build && cd ../client && npm run build && cd ../../ && node postbuild.js`
22 error Exit status 2
23 error Failed at the monopoly-money@ build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]

I'm running on a Raspberry Pi 3b+ with Raspbian 10, Buster Lite. Any ideas?
thanks,
Mike

**Comment by michaeljandrews** [comment]
Quick update, I started again from scratch and now it the web page is working but nothing happens when I center a name and click the button to create a new game. What could be happening?

**Comment by brentvollebregt** [comment]
Are you running the server? If you look in your browser's dev tools, what is the address that it is requesting?

**Comment by michaeljandrews** [comment]
Hi, thanks for responding! The browser is trying to POST to localhost:5000 and that isn't right. Sounds like something in the environment variables. What do you think?

FYI: moved the installation to a Raspberry Pi 4, Raspbian 10 Lite (CLI only), node v12.18.3, npm 6.14.6

**Comment by brentvollebregt** [comment]
No, that looks completely fine - by default the server runs on [port 5000](https://github.com/brentvollebregt/monopoly-money/blob/master/packages/server/src/config.ts#L8) so unless you have changed the port value, this will be fine.

Back to my most recent reply: Are you running the server?

**Comment by michaeljandrews** [comment]
Yes, the server is running. Here's the output after npm start

> monopoly-money@ start /home/pi/monopoly-money
> node packages/server/build

config.server.allowed_origins has not been set. This is the equivalent of setting CORS to *
Listening on 5000

**Comment by michaeljandrews** [comment]
Forgot to mention in the last post, the server is running on a different machine (10.1.1.13) not localhost

**Comment by brentvollebregt** [comment]
Oh right, I had assumed you were running the client and the server on the same machine (reasonable for the info given imo).

[REACT_APP_API_ROOT](https://github.com/brentvollebregt/monopoly-money/blob/master/packages/client/.env.example#L1) defines the address the client should use when contacting the server as defined in the README:

> REACT_APP_API_ROOT (optional): The route that the client requests. Not setting this will default to window.location.origin.

**Comment by michaeljandrews** [comment]
Ok, I updated the client .env file as follows and still getting the same result. 
 REACT_APP_API_ROOT=http://10.1.1.13:5000
 REACT_APP_GOOGLE_ANALYTICS_TRACKING_ID=UA-XXXXXXXXX-X

Here's more from Firefox
<img width="1029" alt="Screen Shot 2020-08-28 at 11 45 59 AM" src="https://user-images.githubusercontent.com/58296371/91587018-307fd580-e924-11ea-9167-ae4632b325b4.png">
Interesting that it is pulling the screenshot images from your web site!

**Comment by michaeljandrews** [comment]
I think I figured out why the REACT_APP_API_ROOT isn't updating. The path to the .env files is incorrect, so they are not being found. To test this, I added PORT=5001 to the server .env file. The server still started on port 5000. When I moved the server .env file to the root level of the project, it started on port 5001. Looking at the code now to figure out where the client is attempting to load its .env file from.

**Comment by michaeljandrews** [comment]
Ok, it's working now. The REACT_APP_API_ROOT parameter isn't needed after moving the server .env file. It resulted it the URL getting doubled up. Thanks for the help!

**Comment by brentvollebregt** [comment]
I'm a bit confused, I just ran `npm run server:dev` and `npm run client:dev` and the environment variables are being used. I then ran `npm build` and `npm start` (after stopping the dev processes) and the environment variables are also being used here.

Could you provide some steps to reproduce the issue you are/were facing?

**Comment by michaeljandrews** [comment]
Sure! Maybe some of this could be useful in updating the documentation. I'm a good test case since this is my first encounter with node.js. I looked and the code and realized what I was doing wrong. I was starting the server from the root level of the project, not from within the packages/server directory. This was causing it to look for the .env file at the root level. The instructions provided say to enter the server and client package directories and copy the .env files from the examples in each. Once that was done, the natural next-step was to back up to the root level before running npm run build and npm start.
    Anyway, as a result of all this experimenting I now have a complete step-by-step installation guide for Raspberry Pi and would be happy to add it to the project as a wiki page. Sound good? Also, I'd like to find out more about how to use the development tools, any suggestions?

**Comment by brentvollebregt** [comment]
Hmm, this might be a Linux thing. I run the `npm run server:dev` and `npm run client:dev` commands from the root and it works fine. 

You saying that you copied the files inside of the package directories and then moving back up is what I expected; I have done that on my Windows machine and it works fine.

In terms of development, typically the `npm run server:dev` and `npm run client:dev` commands will suffice but if you need to go down into the packages for the .env files to work, you can use:
- client: `npm start` (typical create-react-app development)
- server: `npm run dev` (hot reloading)

**Comment by brentvollebregt** [comment]
Sorry, missed this:

> Interesting that it is pulling the screenshot images from your web site!

I would have done this to make it easier to throw images around and not bulk up the repo. I could make a folder internally to hold these.

**Comment by michaeljandrews** [comment]
Hi! I can't figure out how to request a change to the wiki pages, so I created the install instructions on the wiki page of my fork. [https://github.com/michaeljandrews/monopoly-money/wiki/Install-Monopoly-Money-on-a-Raspberry-Pi](url) Let me know if you have any questions and feel free to copy as much as you like!

**Comment by brentvollebregt** [comment]
@michaeljandrews it's been a while but I would like to say thank you for this! The email notification for your last comment has been sitting on my to-do list for quite some time and I have finally gotten around to actioning it.

The page is at https://github.com/brentvollebregt/monopoly-money/wiki/Setup-on-Raspberry-Pi
