### ISSUE TITLE
request

### ISSUE THREAD

**Issue by AndCouvel** [brentvollebregt/monopoly-money#52]
Hey! Is there any chance to get this on a iOS app or app in a future? love this web.

**Comment by brentvollebregt** [comment]
An Individual Developer Account, required for distribution via the app store, goes for an annual fee of USD$99. At the moment this app is completely free and I make nothing from it - so this fee is too steep sorry. I also do not own the hardware required to develop an iOS application. 

> Great to hear you like the app!
