### ISSUE TITLE
Node Engine Support

### ISSUE THREAD

**Issue by ndmax** [brentvollebregt/monopoly-money#54]
I have monoply-money deployed on my home network, and it literally puts Monopoly on the table for family game night.  Thank you @brentvollebregt for this awesome project - the functionality for playing the game is really well executed.

Not really an issue or bug, but with the end of life for [Node 16 LTS](https://nodejs.org/en/blog/announcements/nodejs16-eol), are there any plans to bump [current requirements](https://github.com/brentvollebregt/monopoly-money/blob/master/package.json#L28) to [Node 20 (LTS)](https://nodejs.org/en/blog/release/v20.17.0)?

I tried just updating `package.json` to Node 22 / NPM 10 (which is just what was active on my system at the moment):
```
"engines": {
    "node": "22.x",
    "npm": "10.x"
  }
```
But got the following error on `npm run build`

```
Node.js v22.9.0
npm error Lifecycle script `build` failed with error:
npm error code 1
npm error path /home/.../monopoly-money/packages/client
npm error workspace client2@0.1.0
npm error location /home/.../monopoly-money/packages/client
npm error command failed
npm error command sh -c react-scripts build
```

**Comment by brentvollebregt** [comment]
Thanks for the feedback, it's awesome to hear 😃 

I hadn't planned to upgrade the supported node version but with support ending soon, that sounds like a good idea. It would also be a good opportunity to migrate from react-scripts to vite.

In the meantime, using the Dockerfile should still work (assuming docker is available). Using docker will mean you don't need to install node 16 on your machine.

**Comment by brentvollebregt** [comment]
Was no easy path, but we are running Node 22 now 🥳

**Comment by ndmax** [comment]
Just updated - working great!
