### ISSUE TITLE
Numeric keyboard

### ISSUE THREAD

**Issue by ThangEthan** [brentvollebregt/monopoly-money#9]
<NumberFormat
        allowNegative={false}
        thousandSeparator={true}
        prefix="$"
        id={id}
        value={inputValue}
        onValueChange={({ value }: NumberFormatValues) => setInputValue(value)}
        className="form-control text-center w-100"
        autoComplete="off"
        getInputRef={numberInputRef}
        inputMode="decimal"
/>
inputMode="decimal" will give you the numeric keyboard to input money.

**Comment by brentvollebregt** [comment]
Which device and browser are you using? I'm using Chrome on Android and the number input is used.

**Comment by ThangEthan** [comment]
I use IOS. It happen on both Safari and Chrome

**Comment by brentvollebregt** [comment]
I can reproduce this, cheers for pointing it out.
I'll look into this when I can get my hands on an Apple device.

**Comment by brentvollebregt** [comment]
@ThangEthan are you able to checkout develop and try it?

**Comment by brentvollebregt** [comment]
@ThangEthan I put the changes into master to make it easier to test - has it changed your input type?

**Comment by brentvollebregt** [comment]
Just got hold of a device running a later version of iOS and it seems to be fine.

Let me know if it isn't working or I missed something and I can reopen the issue.
